import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../scss/style.css";
import TopHeader from "./components/TopHeader";
import MainHeader from "./components/MainHeader";
import "/public/js/main.js"
import FooterMain from "./components/Footer";
import FooterBottom from "./components/FooterBottom";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Medixi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <TopHeader />
        <MainHeader />
        {children}
        <FooterMain />
        <FooterBottom />
      </body>
    </html>
  );
}
